services:
  api:
    build: .
    container_name: documind_api
    network_mode: "host"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - RAW_DATA_PATH=data/input_data
      # We exlude ollama from the dockerfile to allow our app run on GPU (since ollama needs to be installed on the host machine to access the GPU)
      # So docker will communicate using port 11434
      - OLLAMA_HOST=http://localhost:11434
      - LLM_MODEL=phi3.5
